### ISSUE TITLE
Missing support for messagedialog window

### ISSUE THREAD

**Issue by pansy27** [phocus/gtk#13]
Hello. 

I was messing with phocus colors and it seems like it lacks support for "messagedialog" windows. Changing theme colors have absolutely no effect on messagedialog windows. Here are some screenshots to explain what i mean:

![8OqM2](https://user-images.githubusercontent.com/88635622/162633301-3d905049-7d44-48bd-9e51-826be5970947.png)
^ messagedialog window on default phocus 
<br>
![23_41_27](https://user-images.githubusercontent.com/88635622/162633434-4f9de263-a9eb-4397-9412-f111a04720ea.png)
^ messagedialog window stays same even after changing colors
<br>
I tried adding the following code to allow theming with variables:
<br>
```css
@use '../colors';

messagedialog {
    background: colors.$surface-weak;
    color: colors.$black-strong;
    border: 0.2em solid colors.$black-weakest;
        box.vertical {
                padding-top: 0.2em;
            }
        button {
            margin: 0em 0.3em 0.3em 0.3em;
            border: none;
            background: colors.$black-weakest;
            transition: background 170ms ease-out;
          &:hover:not(:active) {
                background: colors.$black-weak;
        }
    }
  }
```
<br>
Result:

![23_50_26](https://user-images.githubusercontent.com/88635622/162633859-3072c441-d154-4c93-a9ef-a15df6c982ff.png)

This is on commit 996f644
